#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
from collections import defaultdict
from dataclasses import asdict, dataclass
from pathlib import Path
from statistics import mean
from typing import Any

BLOCK_COMMENT_RE = re.compile(r"/\*.*?\*/", re.S)
LINE_COMMENT_RE = re.compile(r"(^|\s)//.*$", re.M)


@dataclass
class DupGroup:
    kind: str
    hash: str
    occurrences: int
    modules: list[str]
    suggested_package: str
    representative_path: str
    paths: list[str]


def read_text(path: Path) -> str:
    try:
        return path.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return path.read_text(encoding="latin-1")


def normalize_code(content: str) -> str:
    without_block = BLOCK_COMMENT_RE.sub("", content)
    without_line = LINE_COMMENT_RE.sub("", without_block)
    return "\n".join(line.strip() for line in without_line.splitlines() if line.strip())


def module_from_path(path: Path, src_root: Path) -> str:
    rel = path.relative_to(src_root)
    parts = rel.parts
    if parts[0] == "modules" and len(parts) >= 2:
        return parts[1]
    if parts[0] == "pages":
        return "pages"
    if parts[0] == "components":
        return "components"
    return parts[0]


def suggest_package(paths: list[str]) -> str:
    joined = " ".join(paths)
    if "/components/" in joined:
        return "@semcod/ui-components"
    if "/types" in joined or ".types." in joined:
        return "@semcod/contracts-types"
    if "/helpers/" in joined or "/utils/" in joined:
        return "@semcod/ts-utils"
    return "@semcod/shared-core"


def count_lines(path: Path) -> int:
    return read_text(path).count("\n") + 1


def iter_ts_files(src_root: Path) -> list[Path]:
    exts = {".ts", ".tsx", ".js", ".jsx"}
    result: list[Path] = []
    for path in src_root.rglob("*"):
        if path.suffix not in exts:
            continue
        name = path.name
        if name.endswith(".test.ts") or name.endswith(".spec.ts"):
            continue
        if "__tests__" in path.parts:
            continue
        if "generated" in path.parts:
            continue
        result.append(path)
    return result


def render_markdown(groups: list[DupGroup]) -> str:
    lines = [
        "# Shared TypeScript Package Candidates",
        "",
        "Generated by scripts/legacy_bridge/detect_shared_ts_packages.py.",
        "",
        "| kind | occurrences | modules | suggested package | representative |",
        "|---|---:|---|---|---|",
    ]
    for group in groups:
        lines.append(
            f"| {group.kind} | {group.occurrences} | {', '.join(group.modules)} | {group.suggested_package} | {group.representative_path} |"
        )

    lines.extend([
        "",
        "## Recommendation",
        "",
        "Start with groups that appear in at least 3 modules and have stable helper/type semantics.",
        "",
    ])
    return "\n".join(lines)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Detect duplicate TS units that should become shared packages")
    parser.add_argument("--repo-root", required=True, help="path to repository root")
    parser.add_argument("--output-dir", default="migration", help="output directory relative to repo root if not absolute")
    parser.add_argument("--basename", default="shared-ts-candidates", help="basename for generated files")
    parser.add_argument("--min-occurrences", type=int, default=2, help="minimum duplicate count to report")
    parser.add_argument("--min-modules-by-name", type=int, default=3, help="minimum module count for filename-pattern candidates")
    parser.add_argument("--stdout", action="store_true", help="print JSON payload to stdout")
    return parser.parse_args()


def analyze(repo_root: Path, min_occurrences: int, min_modules_by_name: int) -> list[DupGroup]:
    src_root = repo_root / "frontend" / "src"
    if not src_root.exists():
        raise ValueError(f"src root not found: {src_root}")

    buckets: dict[str, list[Path]] = defaultdict(list)
    files = iter_ts_files(src_root)
    for path in files:
        normalized = normalize_code(read_text(path))
        if len(normalized) < 120:
            continue
        digest = hashlib.sha1(normalized.encode("utf-8")).hexdigest()
        buckets[digest].append(path)

    groups: list[DupGroup] = []
    for digest, paths in buckets.items():
        if len(paths) < min_occurrences:
            continue
        rel_paths = [str(p.relative_to(repo_root)).replace("\\", "/") for p in sorted(paths)]
        modules = sorted({module_from_path(p, src_root) for p in paths})
        groups.append(
            DupGroup(
                kind="exact-duplicate",
                hash=digest,
                occurrences=len(paths),
                modules=modules,
                suggested_package=suggest_package(rel_paths),
                representative_path=rel_paths[0],
                paths=rel_paths,
            )
        )

    by_filename: dict[str, list[Path]] = defaultdict(list)
    for path in files:
        try:
            rel = path.relative_to(src_root)
        except ValueError:
            continue
        if rel.parts and rel.parts[0] == "modules":
            by_filename[path.name].append(path)

    for filename, paths in by_filename.items():
        if len(paths) < min_modules_by_name:
            continue
        modules = sorted({module_from_path(p, src_root) for p in paths})
        if len(modules) < min_modules_by_name:
            continue
        avg_lines = mean(count_lines(p) for p in paths)
        if avg_lines < 15:
            continue
        rel_paths = [str(p.relative_to(repo_root)).replace("\\", "/") for p in sorted(paths)]
        stable_hash = hashlib.sha1(("filename:" + filename).encode("utf-8")).hexdigest()
        groups.append(
            DupGroup(
                kind="filename-pattern",
                hash=stable_hash,
                occurrences=len(paths),
                modules=modules,
                suggested_package=suggest_package(rel_paths),
                representative_path=rel_paths[0],
                paths=rel_paths,
            )
        )

    groups.sort(key=lambda g: (g.occurrences, len(g.modules)), reverse=True)
    return groups


def main() -> int:
    args = parse_args()
    repo_root = Path(args.repo_root).resolve()
    if not repo_root.exists() or not repo_root.is_dir():
        print(f"[ERROR] repo root not found: {repo_root}")
        return 1

    try:
        groups = analyze(repo_root, args.min_occurrences, args.min_modules_by_name)
    except ValueError as exc:
        print(f"[ERROR] {exc}")
        return 1

    payload = [asdict(group) for group in groups]
    if args.stdout:
        print(json.dumps(payload, indent=2, ensure_ascii=False))
        return 0

    output_dir = Path(args.output_dir)
    if not output_dir.is_absolute():
        output_dir = repo_root / output_dir
    output_dir.mkdir(parents=True, exist_ok=True)

    out_json = output_dir / f"{args.basename}.json"
    out_md = output_dir / f"{args.basename}.md"

    out_json.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    out_md.write_text(render_markdown(groups), encoding="utf-8")

    print(f"[INFO] wrote {out_json}")
    print(f"[INFO] wrote {out_md}")
    print(f"[INFO] duplicate groups found: {len(groups)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
